server:
  port: ${EVENT_SERVICE_PORT}
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
api:
  url:
    categories: https://kudago.com/public-api/v1.4/event-categories
    locations: https://kudago.com/public-api/v1.4/locations
    events: https://kudago.com/public-api/v1.4/events/?fields=id,title,price,location,category
    currencies: http://localhost:8080/currencies/convert
application:
  security:
    jwt:
      secret-key: ${SECURITY_SECRET_KEY}
      ttl: 600000
  executors:
    scheduler:
      interval: 1h
